DROP TABLE IF EXISTS users, categories, events;
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(256)                            NOT NULL,
    email VARCHAR(128) UNIQUE                     NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(256) UNIQUE                     NOT NULL,
    CONSTRAINT categories_pk PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS events
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation          VARCHAR(1024)               NOT NULL,
    category_id         BIGINT                      NOT NULL,
    confirmed_requests  BIGINT,
    created_on          TIMESTAMP WITHOUT TIME ZONE,
    description         VARCHAR(4096),
    event_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id        BIGINT                      NOT NULL,
    lat                 REAL                        NOT NULL,
    lon                 REAL                        NOT NULL,
    paid                BOOL                        NOT NULL,
    participant_limit   BIGINT,
    published_on        TIMESTAMP WITHOUT TIME ZONE,
    request_moderation  BOOL,
    state               VARCHAR(64),
    title               VARCHAR(128)                NOT NULL,
    views               BIGINT,

    CONSTRAINT events_pk PRIMARY KEY (id),
    CONSTRAINT fk_category_id FOREIGN KEY (category_id)
    REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_initiator_id FOREIGN KEY (initiator_id)
    REFERENCES users (id) ON DELETE CASCADE,
    );

CREATE TABLE IF NOT EXISTS compilations
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(256),
    pinned  BOOL,
    CONSTRAINT compilations_pk PRIMARY KEY (id)
    );